/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Miléd Hammoud (https://sketchfab.com/Miled)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/7280f6200bf74e50bc80e4637ace8fea
title: Diamond
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/diamond/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.45}>
            <group position={[0, 0, 98.59]}>
              <mesh
                geometry={nodes["Cylinder001_Material_#27_0"].geometry}
                material={materials.Material_27}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/diamond/scene.gltf");
