/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: T.Koeniger (https://sketchfab.com/3D-hannover)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/buddha-four-faces-18405445c05e48fabbc915d69ae2ccc2
title: Buddha - Four Faces
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/buddha_four_faces/scene.gltf");
  const args = nodes.Object_2.geometry;

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.9, -1.28]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
          castShadow
          receiveShadow
        />

        <mesh
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={nodes.Object_5.material}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/buddha_four_faces/scene.gltf");
