/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: T.Koeniger (https://sketchfab.com/3D-hannover)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/buddha-four-faces-18405445c05e48fabbc915d69ae2ccc2
title: Buddha - Four Faces
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useControls } from "leva";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes } = useGLTF("/buddha_four_faces/scene.gltf");

  const material = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color("#ccddf0").convertSRGBToLinear(),
    roughness: 0.2,
    clearcoat: 1,
    clearcoatRoughness: 0,
    transmission: 0.7,
    metalness: 0.6,
    ior: 0.1,
    envMapIntensity: 25,
    attenuationTint: "red",
    attenuationDistance: 1,
    thickness: 2,
    reflectivity: 2,
    envMaps: "reflect",
    emissive: "#000000",
    emissiveIntensity: 1,
    sheen: 1,
    sheenColor: "#FFFFFF",
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.9, -1.28]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          // material={nodes.Object_2.material}
          castShadow
          receiveShadow
          material={material}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          // material={nodes.Object_3.material}
          castShadow
          receiveShadow
          material={material}
        />

        <mesh
          geometry={nodes.Object_4.geometry}
          // material={nodes.Object_4.material}
          castShadow
          receiveShadow
          material={material}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          // material={nodes.Object_5.material}
          castShadow
          receiveShadow
          material={material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/buddha_four_faces/scene.gltf");
